FROM node:22-alpine

WORKDIR /app

RUN corepack enable && apk add --no-cache postgresql18-client

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/database-backup/package.json apps/database-backup/package.json
RUN pnpm install --frozen-lockfile --prod --ignore-scripts --filter database-backup...

COPY apps/database-backup apps/database-backup
CMD ["pnpm", "--filter", "database-backup", "start"]
