import { Injectable, Logger, ServiceUnavailableException } from '@nestjs/common';
import type { AggregatedIngredient, Dish } from '@cart/shared';
import {
  INSTACART_API_BASE_URL,
  INSTACART_API_KEY,
  INSTACART_USE_REAL_PROVIDER,
} from '../matching/matching.constants';
import type { CartHandoffResult } from './cart-export.types';

type InstacartProductsLinkResponse = {
  products_link_url?: string;
};

type InstacartLineItem = {
  name: string;
  display_text?: string;
  line_item_measurements?: Array<{
    quantity: number;
    unit: string;
  }>;
};

@Injectable()
export class InstacartCartExportProvider {
  private readonly logger = new Logger(InstacartCartExportProvider.name);

  isEnabled() {
    return Boolean(INSTACART_USE_REAL_PROVIDER && INSTACART_API_KEY);
  }

  async createShoppingList(input: {
    cartId: string;
    title: string;
    overview: AggregatedIngredient[];
    dishes: Dish[];
  }): Promise<CartHandoffResult> {
    if (!this.isEnabled()) {
      throw new ServiceUnavailableException(
        'Instacart handoff is not configured right now.',
      );
    }

    const response = await fetch(
      `${INSTACART_API_BASE_URL}/idp/v1/products/products_link`,
      {
        method: 'POST',
        headers: {
          Accept: 'application/json',
          Authorization: `Bearer ${INSTACART_API_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          title: input.title,
          link_type: 'shopping_list',
          expires_in: 30,
          instructions: this.buildInstructions(input.dishes),
          line_items: input.overview.map((ingredient) =>
            this.toLineItem(ingredient),
          ),
        }),
      },
    );

    if (!response.ok) {
      const errorText = await response.text();
      this.logger.warn(
        `Instacart shopping list creation failed status=${response.status} body=${errorText.slice(0, 400)}`,
      );
      throw new ServiceUnavailableException(
        'Instacart handoff failed. Try again later or use Kroger for this demo.',
      );
    }

    const payload = (await response.json()) as InstacartProductsLinkResponse;

    if (!payload.products_link_url) {
      throw new ServiceUnavailableException(
        'Instacart handoff did not return a shopping list URL.',
      );
    }

    return {
      externalUrl: payload.products_link_url,
      externalReferenceId: input.cartId,
    };
  }

  private toLineItem(ingredient: AggregatedIngredient): InstacartLineItem {
    const unit = this.toInstacartUnit(ingredient.unit);
    const quantity = this.toQuantity(ingredient.total_amount);
    const displayText = `${quantity} ${unit} ${ingredient.canonical_ingredient}`;

    return {
      name: ingredient.canonical_ingredient,
      display_text: displayText,
      line_item_measurements: [
        {
          quantity,
          unit,
        },
      ],
    };
  }

  private buildInstructions(dishes: Dish[]) {
    const names = dishes.map((dish) => dish.name).filter(Boolean);
    if (names.length === 0) {
      return ['Generated by Chef from a meal plan.'];
    }

    return [`Generated by Chef for: ${names.join(', ')}.`];
  }

  private toQuantity(value: number) {
    if (!Number.isFinite(value) || value <= 0) {
      return 1;
    }

    return Number(value.toFixed(2));
  }

  private toInstacartUnit(unit: string) {
    const normalizedUnit = unit.trim().toLowerCase();
    const units: Record<string, string> = {
      unit: 'each',
      each: 'each',
      ct: 'each',
      count: 'each',
      tbsp: 'tablespoon',
      tablespoon: 'tablespoon',
      tablespoons: 'tablespoon',
      tsp: 'teaspoon',
      teaspoon: 'teaspoon',
      teaspoons: 'teaspoon',
      cup: 'cup',
      cups: 'cup',
      oz: 'ounce',
      ounce: 'ounce',
      ounces: 'ounce',
      lb: 'pound',
      lbs: 'pound',
      pound: 'pound',
      pounds: 'pound',
      g: 'gram',
      gram: 'gram',
      grams: 'gram',
      kg: 'kilogram',
      kilogram: 'kilogram',
      kilograms: 'kilogram',
      ml: 'milliliter',
      milliliter: 'milliliter',
      milliliters: 'milliliter',
      l: 'liter',
      liter: 'liter',
      liters: 'liter',
    };

    return units[normalizedUnit] ?? 'each';
  }
}
